# Generated by Django 2.2.5 on 2021-01-08 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_auto_20210109_0530'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='cpation',
            new_name='caption',
        ),
    ]
