# Generated by Django 2.2.5 on 2021-01-08 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_auto_20210109_0517'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='check_out',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='check_in',
            field=models.DateField(null=True),
        ),
    ]
